spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=NEVER
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
dnf.api-key=${dnf_api}
riot.api-key=${riot_api}
upload.path=/app/uploads/profile
agora.app-id=${agora_id}
agora.app-certificate=${agora_certificate}
lostark.base-url=${lostark_base}
lostark.api-key=${lostark_api}
maple.api.key=${maple_api}


spring.cache.type=caffeine

server.port=8080

# 최대 500개, 1시간까지 저장
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h



